// Grammar question bank for the interactive quiz, tagged by CEFR level so
// practice lines up with the lessons. Each item: a sentence with a gap,
// options, the correct index, and a short explanation.

import type { GrammarLevel } from "./lessons";

export interface GrammarQuestion {
  id: string;
  level: GrammarLevel;
  topic: string;
  prompt: string; // use ___ for the gap
  options: string[];
  answer: number; // index into options
  explain: string;
}

export const GRAMMAR_QUESTIONS: GrammarQuestion[] = [
  // ───────── A2 ─────────
  {
    id: "a1",
    level: "A2",
    topic: "Present simple vs continuous",
    prompt: "Listen! The baby ___.",
    options: ["cries", "is crying", "cry", "cried"],
    answer: 1,
    explain: "Happening right now → present continuous (is crying).",
  },
  {
    id: "a2",
    level: "A2",
    topic: "Past simple",
    prompt: "We ___ to Rome last year.",
    options: ["go", "went", "gone", "were go"],
    answer: 1,
    explain: "Finished past time (last year) + irregular go → went.",
  },
  {
    id: "a3",
    level: "A2",
    topic: "Articles",
    prompt: "She is ___ honest person.",
    options: ["a", "an", "the", "—"],
    answer: 1,
    explain: "‘honest’ starts with a vowel sound (silent h) → an.",
  },
  {
    id: "a4",
    level: "A2",
    topic: "there is / there are",
    prompt: "There ___ any sugar left.",
    options: ["isn't", "aren't", "weren't", "haven't"],
    answer: 0,
    explain: "Sugar is uncountable (singular) → there isn't.",
  },
  {
    id: "a5",
    level: "A2",
    topic: "Quantifiers",
    prompt: "There isn't ___ milk left.",
    options: ["many", "much", "a few", "several"],
    answer: 1,
    explain: "Milk is uncountable → much (not many).",
  },
  {
    id: "a6",
    level: "A2",
    topic: "Comparatives",
    prompt: "This route is ___ than the other one.",
    options: ["more fast", "faster", "fastest", "more faster"],
    answer: 1,
    explain: "Short adjective → -er: fast → faster.",
  },
  {
    id: "a7",
    level: "A2",
    topic: "Prepositions of time",
    prompt: "The meeting is ___ Monday morning.",
    options: ["in", "at", "on", "by"],
    answer: 2,
    explain: "Days and dates take ‘on’.",
  },
  {
    id: "a8",
    level: "A2",
    topic: "going to vs will",
    prompt: "Look at those clouds — it ___ rain.",
    options: ["will", "is going to", "rains", "would"],
    answer: 1,
    explain: "Prediction from present evidence → be going to.",
  },

  // ───────── B1 ─────────
  {
    id: "b1",
    level: "B1",
    topic: "Present perfect",
    prompt: "I ___ in London since 2019.",
    options: ["live", "have lived", "lived", "am living"],
    answer: 1,
    explain: "‘since 2019’ links past to now → present perfect.",
  },
  {
    id: "b2",
    level: "B1",
    topic: "Present perfect",
    prompt: "___ you ever ___ sushi?",
    options: ["Did / eat", "Have / eaten", "Do / eat", "Has / ate"],
    answer: 1,
    explain: "Life experience with ‘ever’ → Have you eaten…?",
  },
  {
    id: "b3",
    level: "B1",
    topic: "Past continuous",
    prompt: "I ___ dinner when the phone rang.",
    options: ["cooked", "was cooking", "have cooked", "cook"],
    answer: 1,
    explain: "Action in progress interrupted by another → past continuous.",
  },
  {
    id: "b4",
    level: "B1",
    topic: "First conditional",
    prompt: "If it rains tomorrow, we ___ home.",
    options: ["would stay", "will stay", "stayed", "stay"],
    answer: 1,
    explain: "Real future → if + present, will + verb.",
  },
  {
    id: "b5",
    level: "B1",
    topic: "Second conditional",
    prompt: "If I ___ more time, I would travel more.",
    options: ["have", "had", "will have", "would have"],
    answer: 1,
    explain: "Unreal present → if + past simple, would + verb.",
  },
  {
    id: "b6",
    level: "B1",
    topic: "used to",
    prompt: "I ___ play tennis, but I stopped years ago.",
    options: ["use to", "used to", "am used to", "was used to"],
    answer: 1,
    explain: "Past habit no longer true → used to + base verb.",
  },
  {
    id: "b7",
    level: "B1",
    topic: "Modals",
    prompt: "You ___ smoke in here — it's not allowed.",
    options: ["mustn't", "don't have to", "shouldn't have", "couldn't"],
    answer: 0,
    explain: "Prohibition → mustn't. ‘don't have to’ = optional.",
  },
  {
    id: "b8",
    level: "B1",
    topic: "Gerund vs infinitive",
    prompt: "I look forward to ___ from you.",
    options: ["hear", "hearing", "heard", "be hearing"],
    answer: 1,
    explain: "‘look forward to’ + -ing (to is a preposition here).",
  },
  {
    id: "b9",
    level: "B1",
    topic: "Gerund vs infinitive",
    prompt: "She decided ___ a new language.",
    options: ["learning", "to learn", "learn", "learned"],
    answer: 1,
    explain: "‘decide’ is followed by the infinitive: to learn.",
  },
  {
    id: "b10",
    level: "B1",
    topic: "Relative clauses",
    prompt: "That's the woman ___ helped me.",
    options: ["which", "who", "whom", "where"],
    answer: 1,
    explain: "‘who’ refers to people as the subject.",
  },
  {
    id: "b11",
    level: "B1",
    topic: "Dependent prepositions",
    prompt: "I'm really good ___ remembering names.",
    options: ["in", "on", "at", "for"],
    answer: 2,
    explain: "‘good at + -ing’ is the fixed pattern.",
  },
  {
    id: "b12",
    level: "B1",
    topic: "Future forms",
    prompt: "I ___ Sara at five — we arranged it yesterday.",
    options: ["am meeting", "meet", "will meet", "meets"],
    answer: 0,
    explain: "Fixed arrangement with a person/time → present continuous.",
  },

  // ───────── B2 ─────────
  {
    id: "c1",
    level: "B2",
    topic: "Present perfect continuous",
    prompt: "My eyes hurt — I ___ on the computer all day.",
    options: ["worked", "have been working", "work", "had worked"],
    answer: 1,
    explain: "Duration up to now (and its effect) → present perfect continuous.",
  },
  {
    id: "c2",
    level: "B2",
    topic: "Past perfect",
    prompt: "By the time we arrived, the film ___.",
    options: ["already started", "had already started", "has started", "starts"],
    answer: 1,
    explain: "Earlier of two past actions → past perfect.",
  },
  {
    id: "c3",
    level: "B2",
    topic: "Passive voice",
    prompt: "The bridge ___ in 1890.",
    options: ["built", "was built", "is built", "has built"],
    answer: 1,
    explain: "Past passive → was + past participle.",
  },
  {
    id: "c4",
    level: "B2",
    topic: "Passive voice",
    prompt: "English ___ all over the world.",
    options: ["speaks", "is spoken", "spoken", "speaking"],
    answer: 1,
    explain: "Present passive → is + past participle.",
  },
  {
    id: "c5",
    level: "B2",
    topic: "Third conditional",
    prompt: "If I ___ harder, I would have passed.",
    options: ["studied", "had studied", "study", "would study"],
    answer: 1,
    explain: "Unreal past → if + past perfect, would have + participle.",
  },
  {
    id: "c6",
    level: "B2",
    topic: "wish",
    prompt: "I wish I ___ that — it was a mistake.",
    options: ["didn't say", "hadn't said", "don't say", "wouldn't say"],
    answer: 1,
    explain: "Regret about the past → wish + past perfect.",
  },
  {
    id: "c7",
    level: "B2",
    topic: "Reported speech",
    prompt: "He said he ___ tired.",
    options: ["is", "was", "has been", "will be"],
    answer: 1,
    explain: "Reported speech shifts present → past: is → was.",
  },
  {
    id: "c8",
    level: "B2",
    topic: "Reported speech",
    prompt: "She asked where I ___.",
    options: ["do live", "lived", "did live", "live"],
    answer: 1,
    explain: "Reported questions use statement word order, tense back: lived.",
  },
  {
    id: "c9",
    level: "B2",
    topic: "Modals of deduction",
    prompt: "The lights are off — they ___ home already.",
    options: ["must have gone", "can go", "must go", "should go"],
    answer: 0,
    explain: "Confident deduction about the past → must have + participle.",
  },
  {
    id: "c10",
    level: "B2",
    topic: "Causative",
    prompt: "I had my car ___ yesterday.",
    options: ["repair", "repaired", "to repair", "repairing"],
    answer: 1,
    explain: "Causative: have + object + past participle (someone did it for me).",
  },
  {
    id: "c11",
    level: "B2",
    topic: "Degree structures",
    prompt: "It was ___ cold that we went home early.",
    options: ["so", "such", "too", "very"],
    answer: 0,
    explain: "‘so + adjective + that…’. ‘such’ needs a noun.",
  },
  {
    id: "c12",
    level: "B2",
    topic: "Future perfect",
    prompt: "By next June I ___ my degree.",
    options: ["will finish", "will have finished", "finish", "am finishing"],
    answer: 1,
    explain: "Completed before a future point → future perfect.",
  },

  // ───────── C1 ─────────
  {
    id: "d1",
    level: "C1",
    topic: "Inversion",
    prompt: "Never ___ such a beautiful view.",
    options: ["I have seen", "have I seen", "I saw", "did I saw"],
    answer: 1,
    explain: "Negative adverbial first → invert: Never have I seen…",
  },
  {
    id: "d2",
    level: "C1",
    topic: "Inversion",
    prompt: "No sooner had I sat down ___ the phone rang.",
    options: ["than", "then", "when", "that"],
    answer: 0,
    explain: "Fixed structure: No sooner … than.",
  },
  {
    id: "d3",
    level: "C1",
    topic: "Cleft sentences",
    prompt: "___ I really need is a holiday.",
    options: ["That", "What", "Which", "It"],
    answer: 1,
    explain: "wh-cleft for emphasis: What I need is…",
  },
  {
    id: "d4",
    level: "C1",
    topic: "Cleft sentences",
    prompt: "It was John ___ broke the window.",
    options: ["who", "which", "what", "whose"],
    answer: 0,
    explain: "It-cleft emphasising a person → who.",
  },
  {
    id: "d5",
    level: "C1",
    topic: "Mixed conditionals",
    prompt: "If I had saved money, I ___ rich now.",
    options: ["would be", "would have been", "will be", "am"],
    answer: 0,
    explain: "Past condition → present result: would + base verb.",
  },
  {
    id: "d6",
    level: "C1",
    topic: "Connectors",
    prompt: "___ the heavy rain, we went out.",
    options: ["Despite", "Although", "However", "Whereas"],
    answer: 0,
    explain: "‘Despite’ + noun phrase. ‘Although’ needs a clause.",
  },
  {
    id: "d7",
    level: "C1",
    topic: "Connectors",
    prompt: "He's very quiet, ___ his sister is outgoing.",
    options: ["whereas", "despite", "however", "in spite"],
    answer: 0,
    explain: "‘whereas’ links two contrasting clauses.",
  },
];
