// Grammar question bank for the interactive quiz, tagged by CEFR level so
// practice lines up with the lessons. Each item: a sentence with a gap,
// options, the correct index, and a short explanation.

import type { GrammarLevel } from "./lessons";

export interface GrammarQuestion {
  id: string;
  level: GrammarLevel;
  topic: string;
  prompt: string; // use ___ for the gap
  options: string[];
  answer: number; // index into options
  explain: string;
}

export const GRAMMAR_QUESTIONS: GrammarQuestion[] = [
  // ───────── A2 ─────────
  {
    id: "a1",
    level: "A2",
    topic: "Present simple vs continuous",
    prompt: "Listen! The baby ___.",
    options: ["cries", "is crying", "cry", "cried"],
    answer: 1,
    explain: "Happening right now → present continuous (is crying).",
  },
  {
    id: "a2",
    level: "A2",
    topic: "Past simple",
    prompt: "We ___ to Rome last year.",
    options: ["go", "went", "gone", "were go"],
    answer: 1,
    explain: "Finished past time (last year) + irregular go → went.",
  },
  {
    id: "a3",
    level: "A2",
    topic: "Articles",
    prompt: "She is ___ honest person.",
    options: ["a", "an", "the", "—"],
    answer: 1,
    explain: "‘honest’ starts with a vowel sound (silent h) → an.",
  },
  {
    id: "a4",
    level: "A2",
    topic: "there is / there are",
    prompt: "There ___ any sugar left.",
    options: ["isn't", "aren't", "weren't", "haven't"],
    answer: 0,
    explain: "Sugar is uncountable (singular) → there isn't.",
  },
  {
    id: "a5",
    level: "A2",
    topic: "Quantifiers",
    prompt: "There isn't ___ milk left.",
    options: ["many", "much", "a few", "several"],
    answer: 1,
    explain: "Milk is uncountable → much (not many).",
  },
  {
    id: "a6",
    level: "A2",
    topic: "Comparatives",
    prompt: "This route is ___ than the other one.",
    options: ["more fast", "faster", "fastest", "more faster"],
    answer: 1,
    explain: "Short adjective → -er: fast → faster.",
  },
  {
    id: "a7",
    level: "A2",
    topic: "Prepositions of time",
    prompt: "The meeting is ___ Monday morning.",
    options: ["in", "at", "on", "by"],
    answer: 2,
    explain: "Days and dates take ‘on’.",
  },
  {
    id: "a8",
    level: "A2",
    topic: "going to vs will",
    prompt: "Look at those clouds — it ___ rain.",
    options: ["will", "is going to", "rains", "would"],
    answer: 1,
    explain: "Prediction from present evidence → be going to.",
  },

  // ───────── B1 ─────────
  {
    id: "b1",
    level: "B1",
    topic: "Present perfect",
    prompt: "I ___ in London since 2019.",
    options: ["live", "have lived", "lived", "am living"],
    answer: 1,
    explain: "‘since 2019’ links past to now → present perfect.",
  },
  {
    id: "b2",
    level: "B1",
    topic: "Present perfect",
    prompt: "___ you ever ___ sushi?",
    options: ["Did / eat", "Have / eaten", "Do / eat", "Has / ate"],
    answer: 1,
    explain: "Life experience with ‘ever’ → Have you eaten…?",
  },
  {
    id: "b3",
    level: "B1",
    topic: "Past continuous",
    prompt: "I ___ dinner when the phone rang.",
    options: ["cooked", "was cooking", "have cooked", "cook"],
    answer: 1,
    explain: "Action in progress interrupted by another → past continuous.",
  },
  {
    id: "b4",
    level: "B1",
    topic: "First conditional",
    prompt: "If it rains tomorrow, we ___ home.",
    options: ["would stay", "will stay", "stayed", "stay"],
    answer: 1,
    explain: "Real future → if + present, will + verb.",
  },
  {
    id: "b5",
    level: "B1",
    topic: "Second conditional",
    prompt: "If I ___ more time, I would travel more.",
    options: ["have", "had", "will have", "would have"],
    answer: 1,
    explain: "Unreal present → if + past simple, would + verb.",
  },
  {
    id: "b6",
    level: "B1",
    topic: "used to",
    prompt: "I ___ play tennis, but I stopped years ago.",
    options: ["use to", "used to", "am used to", "was used to"],
    answer: 1,
    explain: "Past habit no longer true → used to + base verb.",
  },
  {
    id: "b7",
    level: "B1",
    topic: "Modals",
    prompt: "You ___ smoke in here — it's not allowed.",
    options: ["mustn't", "don't have to", "shouldn't have", "couldn't"],
    answer: 0,
    explain: "Prohibition → mustn't. ‘don't have to’ = optional.",
  },
  {
    id: "b8",
    level: "B1",
    topic: "Gerund vs infinitive",
    prompt: "I look forward to ___ from you.",
    options: ["hear", "hearing", "heard", "be hearing"],
    answer: 1,
    explain: "‘look forward to’ + -ing (to is a preposition here).",
  },
  {
    id: "b9",
    level: "B1",
    topic: "Gerund vs infinitive",
    prompt: "She decided ___ a new language.",
    options: ["learning", "to learn", "learn", "learned"],
    answer: 1,
    explain: "‘decide’ is followed by the infinitive: to learn.",
  },
  {
    id: "b10",
    level: "B1",
    topic: "Relative clauses",
    prompt: "That's the woman ___ helped me.",
    options: ["which", "who", "whom", "where"],
    answer: 1,
    explain: "‘who’ refers to people as the subject.",
  },
  {
    id: "b11",
    level: "B1",
    topic: "Dependent prepositions",
    prompt: "I'm really good ___ remembering names.",
    options: ["in", "on", "at", "for"],
    answer: 2,
    explain: "‘good at + -ing’ is the fixed pattern.",
  },
  {
    id: "b12",
    level: "B1",
    topic: "Future forms",
    prompt: "I ___ Sara at five — we arranged it yesterday.",
    options: ["am meeting", "meet", "will meet", "meets"],
    answer: 0,
    explain: "Fixed arrangement with a person/time → present continuous.",
  },

  // ───────── B2 ─────────
  {
    id: "c1",
    level: "B2",
    topic: "Present perfect continuous",
    prompt: "My eyes hurt — I ___ on the computer all day.",
    options: ["worked", "have been working", "work", "had worked"],
    answer: 1,
    explain: "Duration up to now (and its effect) → present perfect continuous.",
  },
  {
    id: "c2",
    level: "B2",
    topic: "Past perfect",
    prompt: "By the time we arrived, the film ___.",
    options: ["already started", "had already started", "has started", "starts"],
    answer: 1,
    explain: "Earlier of two past actions → past perfect.",
  },
  {
    id: "c3",
    level: "B2",
    topic: "Passive voice",
    prompt: "The bridge ___ in 1890.",
    options: ["built", "was built", "is built", "has built"],
    answer: 1,
    explain: "Past passive → was + past participle.",
  },
  {
    id: "c4",
    level: "B2",
    topic: "Passive voice",
    prompt: "English ___ all over the world.",
    options: ["speaks", "is spoken", "spoken", "speaking"],
    answer: 1,
    explain: "Present passive → is + past participle.",
  },
  {
    id: "c5",
    level: "B2",
    topic: "Third conditional",
    prompt: "If I ___ harder, I would have passed.",
    options: ["studied", "had studied", "study", "would study"],
    answer: 1,
    explain: "Unreal past → if + past perfect, would have + participle.",
  },
  {
    id: "c6",
    level: "B2",
    topic: "wish",
    prompt: "I wish I ___ that — it was a mistake.",
    options: ["didn't say", "hadn't said", "don't say", "wouldn't say"],
    answer: 1,
    explain: "Regret about the past → wish + past perfect.",
  },
  {
    id: "c7",
    level: "B2",
    topic: "Reported speech",
    prompt: "He said he ___ tired.",
    options: ["is", "was", "has been", "will be"],
    answer: 1,
    explain: "Reported speech shifts present → past: is → was.",
  },
  {
    id: "c8",
    level: "B2",
    topic: "Reported speech",
    prompt: "She asked where I ___.",
    options: ["do live", "lived", "did live", "live"],
    answer: 1,
    explain: "Reported questions use statement word order, tense back: lived.",
  },
  {
    id: "c9",
    level: "B2",
    topic: "Modals of deduction",
    prompt: "The lights are off — they ___ home already.",
    options: ["must have gone", "can go", "must go", "should go"],
    answer: 0,
    explain: "Confident deduction about the past → must have + participle.",
  },
  {
    id: "c10",
    level: "B2",
    topic: "Causative",
    prompt: "I had my car ___ yesterday.",
    options: ["repair", "repaired", "to repair", "repairing"],
    answer: 1,
    explain: "Causative: have + object + past participle (someone did it for me).",
  },
  {
    id: "c11",
    level: "B2",
    topic: "Degree structures",
    prompt: "It was ___ cold that we went home early.",
    options: ["so", "such", "too", "very"],
    answer: 0,
    explain: "‘so + adjective + that…’. ‘such’ needs a noun.",
  },
  {
    id: "c12",
    level: "B2",
    topic: "Future perfect",
    prompt: "By next June I ___ my degree.",
    options: ["will finish", "will have finished", "finish", "am finishing"],
    answer: 1,
    explain: "Completed before a future point → future perfect.",
  },

  // ───────── C1 ─────────
  {
    id: "d1",
    level: "C1",
    topic: "Inversion",
    prompt: "Never ___ such a beautiful view.",
    options: ["I have seen", "have I seen", "I saw", "did I saw"],
    answer: 1,
    explain: "Negative adverbial first → invert: Never have I seen…",
  },
  {
    id: "d2",
    level: "C1",
    topic: "Inversion",
    prompt: "No sooner had I sat down ___ the phone rang.",
    options: ["than", "then", "when", "that"],
    answer: 0,
    explain: "Fixed structure: No sooner … than.",
  },
  {
    id: "d3",
    level: "C1",
    topic: "Cleft sentences",
    prompt: "___ I really need is a holiday.",
    options: ["That", "What", "Which", "It"],
    answer: 1,
    explain: "wh-cleft for emphasis: What I need is…",
  },
  {
    id: "d4",
    level: "C1",
    topic: "Cleft sentences",
    prompt: "It was John ___ broke the window.",
    options: ["who", "which", "what", "whose"],
    answer: 0,
    explain: "It-cleft emphasising a person → who.",
  },
  {
    id: "d5",
    level: "C1",
    topic: "Mixed conditionals",
    prompt: "If I had saved money, I ___ rich now.",
    options: ["would be", "would have been", "will be", "am"],
    answer: 0,
    explain: "Past condition → present result: would + base verb.",
  },
  {
    id: "d6",
    level: "C1",
    topic: "Connectors",
    prompt: "___ the heavy rain, we went out.",
    options: ["Despite", "Although", "However", "Whereas"],
    answer: 0,
    explain: "‘Despite’ + noun phrase. ‘Although’ needs a clause.",
  },
  {
    id: "d7",
    level: "C1",
    topic: "Connectors",
    prompt: "He's very quiet, ___ his sister is outgoing.",
    options: ["whereas", "despite", "however", "in spite"],
    answer: 0,
    explain: "‘whereas’ links two contrasting clauses.",
  },

  // ───────── A2 (expanded) ─────────
  { id: "a9", level: "A2", topic: "Present simple vs continuous", prompt: "My brother ___ in a bank.", options: ["work", "works", "working", "is work"], answer: 1, explain: "Third-person singular present simple adds -s → works." },
  { id: "a10", level: "A2", topic: "Present simple vs continuous", prompt: "Be quiet — I ___ to concentrate.", options: ["try", "am trying", "tries", "tried"], answer: 1, explain: "Happening right now → present continuous (am trying)." },
  { id: "a11", level: "A2", topic: "Past simple", prompt: "I ___ go to the party last night.", options: ["didn't", "don't", "wasn't", "haven't"], answer: 0, explain: "Past simple negative = didn't + base verb." },
  { id: "a12", level: "A2", topic: "Past simple", prompt: "She ___ her keys yesterday.", options: ["loses", "lost", "losed", "has lost"], answer: 1, explain: "Finished time (yesterday) + irregular lose → lost." },
  { id: "a13", level: "A2", topic: "Articles", prompt: "He's ___ engineer.", options: ["a", "an", "the", "—"], answer: 1, explain: "‘engineer’ starts with a vowel sound → an." },
  { id: "a14", level: "A2", topic: "Articles", prompt: "Can you close ___ door, please?", options: ["a", "an", "the", "—"], answer: 2, explain: "A specific, known door → the." },
  { id: "a15", level: "A2", topic: "Comparatives", prompt: "This box is ___ than that one.", options: ["heavy", "heavier", "heaviest", "more heavy"], answer: 1, explain: "Short adjective + -er → heavier." },
  { id: "a16", level: "A2", topic: "Superlatives", prompt: "It's the ___ day of the year.", options: ["hot", "hotter", "hottest", "most hot"], answer: 2, explain: "Superlative of a short adjective → -est (hottest)." },
  { id: "a17", level: "A2", topic: "going to vs will", prompt: "Look at those clouds — it ___ rain.", options: ["will", "'s going to", "rains", "is rain"], answer: 1, explain: "Evidence now → going to." },
  { id: "a18", level: "A2", topic: "going to vs will", prompt: "That's the phone. I ___ get it.", options: ["'ll", "'m going to", "get", "am"], answer: 0, explain: "Decision at the moment of speaking → will." },
  { id: "a19", level: "A2", topic: "Prepositions of time", prompt: "The meeting is ___ Monday.", options: ["in", "on", "at", "to"], answer: 1, explain: "Days → on." },
  { id: "a20", level: "A2", topic: "Prepositions of time", prompt: "I wake up ___ 7 o'clock.", options: ["in", "on", "at", "by"], answer: 2, explain: "Clock times → at." },
  { id: "a21", level: "A2", topic: "Quantifiers", prompt: "There isn't ___ milk left.", options: ["some", "any", "many", "a"], answer: 1, explain: "Negative + uncountable → any." },
  { id: "a22", level: "A2", topic: "Quantifiers", prompt: "How ___ people came?", options: ["much", "many", "some", "a lot"], answer: 1, explain: "Countable plural → many." },
  { id: "a23", level: "A2", topic: "there is / there are", prompt: "There ___ two cafés on this street.", options: ["is", "are", "be", "have"], answer: 1, explain: "Plural subject → there are." },
  { id: "a24", level: "A2", topic: "Prepositions of place", prompt: "The keys are ___ the drawer.", options: ["on", "in", "at", "to"], answer: 1, explain: "Inside something → in." },
  { id: "a25", level: "A2", topic: "Adverbs of frequency", prompt: "She ___ late for work.", options: ["is never", "never is", "is ever", "nevers"], answer: 0, explain: "Frequency adverb goes after the verb ‘be’ → is never." },

  // ───────── B1 (expanded) ─────────
  { id: "b13", level: "B1", topic: "Present perfect", prompt: "I've lived here ___ 2019.", options: ["for", "since", "from", "ago"], answer: 1, explain: "A point in time → since." },
  { id: "b14", level: "B1", topic: "Present perfect", prompt: "We've known each other ___ ten years.", options: ["since", "for", "from", "during"], answer: 1, explain: "A length of time → for." },
  { id: "b15", level: "B1", topic: "Present perfect", prompt: "I ___ him yesterday.", options: ["'ve seen", "saw", "seen", "have saw"], answer: 1, explain: "Finished time (yesterday) → past simple, not present perfect." },
  { id: "b16", level: "B1", topic: "Present perfect", prompt: "Have you finished ___?", options: ["yet", "already", "just", "still"], answer: 0, explain: "Questions and negatives use ‘yet’ at the end." },
  { id: "b17", level: "B1", topic: "First conditional", prompt: "If it rains, we ___ at home.", options: ["stay", "will stay", "stayed", "would stay"], answer: 1, explain: "First conditional: if + present, will + base." },
  { id: "b18", level: "B1", topic: "Second conditional", prompt: "If I ___ rich, I'd travel the world.", options: ["am", "were", "will be", "had been"], answer: 1, explain: "Second conditional: if + past (were), would." },
  { id: "b19", level: "B1", topic: "Modals", prompt: "You ___ see a doctor about that cough.", options: ["should", "must", "can", "might"], answer: 0, explain: "Advice → should." },
  { id: "b20", level: "B1", topic: "Modals", prompt: "You ___ wear a seatbelt — it's the law.", options: ["should", "must", "could", "might"], answer: 1, explain: "Strong obligation / rule → must." },
  { id: "b21", level: "B1", topic: "Modals", prompt: "She ___ swim when she was four.", options: ["can", "could", "must", "should"], answer: 1, explain: "Past ability → could." },
  { id: "b22", level: "B1", topic: "Past continuous", prompt: "I was cooking ___ the lights went out.", options: ["while", "when", "during", "as soon"], answer: 1, explain: "A short past action interrupts a longer one → when." },
  { id: "b23", level: "B1", topic: "Past continuous", prompt: "While I ___, the phone rang.", options: ["slept", "was sleeping", "sleep", "had slept"], answer: 1, explain: "Background action in progress → past continuous." },
  { id: "b24", level: "B1", topic: "used to", prompt: "I ___ smoke, but I quit years ago.", options: ["use to", "used to", "am used to", "would used to"], answer: 1, explain: "Past habit that stopped → used to + base verb." },
  { id: "b25", level: "B1", topic: "Future forms", prompt: "I ___ the dentist at 5 tomorrow.", options: ["'m seeing", "'ll see", "see", "will be see"], answer: 0, explain: "A fixed arrangement → present continuous." },
  { id: "b26", level: "B1", topic: "Gerund vs infinitive", prompt: "I enjoy ___ to music.", options: ["listen", "listening", "to listen", "listened"], answer: 1, explain: "‘enjoy’ is followed by the gerund (-ing)." },
  { id: "b27", level: "B1", topic: "Gerund vs infinitive", prompt: "She decided ___ early.", options: ["leaving", "to leave", "leave", "left"], answer: 1, explain: "‘decide’ is followed by the infinitive (to leave)." },
  { id: "b28", level: "B1", topic: "Relative clauses", prompt: "That's the man ___ car was stolen.", options: ["who", "which", "whose", "whom"], answer: 2, explain: "Possession → whose." },
  { id: "b29", level: "B1", topic: "Relative clauses", prompt: "This is the book ___ I told you about.", options: ["who", "which", "whose", "what"], answer: 1, explain: "A thing → which (or that)." },
  { id: "b30", level: "B1", topic: "Dependent prepositions", prompt: "She's really good ___ maths.", options: ["in", "at", "on", "for"], answer: 1, explain: "good at + skill/subject." },
  { id: "b31", level: "B1", topic: "Dependent prepositions", prompt: "I'm interested ___ history.", options: ["on", "in", "at", "for"], answer: 1, explain: "interested in something." },

  // ───────── B2 (expanded) ─────────
  { id: "c13", level: "B2", topic: "Passive voice", prompt: "The bridge ___ in 1990.", options: ["built", "was built", "has built", "is build"], answer: 1, explain: "Past passive = was/were + past participle." },
  { id: "c14", level: "B2", topic: "Passive voice", prompt: "English ___ all over the world.", options: ["speaks", "is spoken", "spoke", "is speak"], answer: 1, explain: "Present passive = is/are + past participle." },
  { id: "c15", level: "B2", topic: "Reported speech", prompt: "She said she ___ tired.", options: ["is", "was", "has been", "will be"], answer: 1, explain: "Reported speech backshifts present → past (was)." },
  { id: "c16", level: "B2", topic: "Reported speech", prompt: "He asked me where I ___.", options: ["live", "lived", "do live", "am living"], answer: 1, explain: "Reported question: backshift and no inversion → I lived." },
  { id: "c17", level: "B2", topic: "Third conditional", prompt: "If I had known, I ___ you.", options: ["would tell", "would have told", "told", "had told"], answer: 1, explain: "Third conditional: if + past perfect, would have + past participle." },
  { id: "c18", level: "B2", topic: "wish", prompt: "I wish I ___ harder for the exam.", options: ["studied", "had studied", "study", "would study"], answer: 1, explain: "Regret about the past → wish + past perfect." },
  { id: "c19", level: "B2", topic: "wish", prompt: "I wish I ___ taller.", options: ["am", "were", "was being", "will be"], answer: 1, explain: "Present unreal wish → wish + past (were)." },
  { id: "c20", level: "B2", topic: "Past perfect", prompt: "When we arrived, the film ___.", options: ["started", "had started", "has started", "was starting"], answer: 1, explain: "An earlier past action → past perfect (had started)." },
  { id: "c21", level: "B2", topic: "Present perfect continuous", prompt: "My eyes hurt — I ___ all day.", options: ["read", "have read", "have been reading", "am reading"], answer: 2, explain: "Recent, ongoing activity → present perfect continuous." },
  { id: "c22", level: "B2", topic: "Modals of deduction", prompt: "She's not answering — she ___ be asleep.", options: ["must", "can't", "should", "would"], answer: 0, explain: "Logical near-certainty → must be." },
  { id: "c23", level: "B2", topic: "Modals of deduction", prompt: "He ___ be hungry; he just ate.", options: ["must", "can't", "should", "might"], answer: 1, explain: "Logically impossible → can't be." },
  { id: "c24", level: "B2", topic: "Causative", prompt: "I ___ my hair cut yesterday.", options: ["had", "did", "made", "cut"], answer: 0, explain: "have something done → had my hair cut." },
  { id: "c25", level: "B2", topic: "Future perfect", prompt: "By 2030, I ___ here for ten years.", options: ["will work", "will have worked", "work", "am working"], answer: 1, explain: "Completed by a future point → future perfect." },
  { id: "c26", level: "B2", topic: "Reported speech", prompt: "He ___ me he was leaving.", options: ["said", "told", "asked", "spoke"], answer: 1, explain: "‘tell’ takes a personal object → told me." },
  { id: "c27", level: "B2", topic: "Passive voice", prompt: "The work ___ finished by Friday.", options: ["must", "must be", "is being", "has"], answer: 1, explain: "Modal passive → must be + past participle." },

  // ───────── C1 (expanded) ─────────
  { id: "d8", level: "C1", topic: "Inversion", prompt: "Never ___ such a beautiful sunset.", options: ["I have seen", "have I seen", "I saw", "did I saw"], answer: 1, explain: "A negative adverbial first triggers inversion → have I seen." },
  { id: "d9", level: "C1", topic: "Inversion", prompt: "Hardly ___ when it started to rain.", options: ["we had left", "had we left", "we left", "did we left"], answer: 1, explain: "Hardly + inversion + past perfect → had we left." },
  { id: "d10", level: "C1", topic: "Cleft sentences", prompt: "___ Anna who broke the vase, not me.", options: ["It was", "It is", "There was", "That was"], answer: 0, explain: "It-cleft for emphasis about the past → It was X who…" },
  { id: "d11", level: "C1", topic: "Cleft sentences", prompt: "___ I really need is a holiday.", options: ["That", "What", "Which", "It"], answer: 1, explain: "What-cleft for emphasis → What I need is…" },
  { id: "d12", level: "C1", topic: "Mixed conditionals", prompt: "If I had saved money, I ___ broke now.", options: ["wouldn't be", "wouldn't have been", "won't be", "am not"], answer: 0, explain: "Past condition → present result: would + base (now)." },
  { id: "d13", level: "C1", topic: "Mixed conditionals", prompt: "If she were more careful, she ___ that mistake.", options: ["wouldn't make", "wouldn't have made", "won't make", "didn't make"], answer: 1, explain: "Present condition → past result: would have + past participle." },
  { id: "d14", level: "C1", topic: "Connectors", prompt: "___ the rain, the match continued.", options: ["Despite", "Although", "However", "Because"], answer: 0, explain: "‘Despite’ is followed by a noun phrase." },
  { id: "d15", level: "C1", topic: "Connectors", prompt: "He failed, ___ he had studied hard.", options: ["despite", "even though", "in spite", "because"], answer: 1, explain: "‘even though’ + clause shows contrast." },
  { id: "d16", level: "C1", topic: "Degree structures", prompt: "It was ___ a boring film that I left.", options: ["so", "such", "very", "too"], answer: 1, explain: "such + (a) + adjective + noun → such a boring film." },
  { id: "d17", level: "C1", topic: "Subjunctive", prompt: "The teacher insisted that he ___ on time.", options: ["is", "be", "was", "being"], answer: 1, explain: "Subjunctive after ‘insist that’ → base form (be)." },
  { id: "d18", level: "C1", topic: "Participle clauses", prompt: "___ tired, she went to bed early.", options: ["Feeling", "Felt", "To feel", "She feeling"], answer: 0, explain: "Participle clause = Because she felt tired → Feeling tired." },
];
